version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_DATABASE=${DB_NAME:-form_vaksin}
      - DB_USERNAME=${DB_USERNAME:-laravelRSIuser}
      - DB_PASSWORD=${DB_PASSWORD:-laravelRSIuser}

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"  # Ganti ke port 3307 untuk avoid konflik dengan MySQL lain
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_NAME:-form_vaksin}
      MYSQL_USER: ${DB_USERNAME:-laravelRSIuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravelRSIuser}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network

# Docker Networks
networks:
  laravel-network:
    driver: bridge

# Volumes
volumes:
  mysql-data:
    driver: local
