name: Deploy Laravel to VPS

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: CI/CD to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            REPO="https://${{ secrets.GIT_TOKEN }}@github.com/Studentalthaf/form-vaksin-RSI.git"
            DIR="${{ secrets.VPS_PATH }}/form-vaksin"
            CONTAINER="laravel_app"
            BRANCH="main"
            echo "Cek git"
            if ! command -v git &>/dev/null; then
              echo "Install git..."
              sudo apt-get update && sudo apt-get install -y git
            fi
            echo "Cek docker"
            if ! command -v docker &>/dev/null; then
              echo "Install docker..."
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker $USER
            fi
            echo "Cek docker compose"
            if ! docker compose version &>/dev/null; then
              echo "Install docker compose plugin..."
              mkdir -p ~/.docker/cli-plugins
              curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                -o ~/.docker/cli-plugins/docker-compose
              chmod +x ~/.docker/cli-plugins/docker-compose
            fi
            echo "Clone atau pull repo"
            if [ ! -d "$DIR/.git" ]; then
              echo "Clone repo..."
              git clone --branch $BRANCH $REPO $DIR
            else
              echo "Pull update..."
              cd $DIR
              git reset --hard HEAD
              git pull origin $BRANCH
            fi
            echo "Menyimpan .env untuk Laravel"
            echo "${{ secrets.LARAVEL_ENV }}" > $DIR/.env
            
            echo "Menyiapkan environment variables untuk Docker Compose"
            cd $DIR
            cat > .env.deploy << EOF
            APP_PORT=${{ secrets.APP_PORT }}
            DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF
            
            echo "Menghentikan container lama (jika ada)"
            docker compose down || true
            
            echo "Membersihkan container dan network lama"
            docker container prune -f
            docker network prune -f
            
            echo "Memulai Docker Compose dengan build ulang"
            docker compose --env-file .env.deploy up -d --build --remove-orphans
            
            echo "Menunggu database siap..."
            sleep 10
            
            echo "Menunggu container laravel_app siap..."
            for i in {1..30}; do
              if docker ps | grep -q laravel_app; then
                echo "Container laravel_app sudah running!"
                break
              fi
              echo "Waiting for container to start... ($i/30)"
              sleep 2
            done
            
            echo "Verifikasi container"
            docker ps
            
            echo "Menunggu PHP-FPM siap..."
            sleep 5
            
            echo "Install composer dependencies"
            docker exec $CONTAINER composer install --optimize-autoloader --no-dev || true
            
            echo "Generate application key"
            docker exec $CONTAINER php artisan key:generate --force
            
            echo "Run database migrations"
            docker exec $CONTAINER php artisan migrate --force
            
            echo "Clear cache"
            docker exec $CONTAINER php artisan config:clear
            docker exec $CONTAINER php artisan cache:clear
            
            echo "Deployment selesai!"
            docker ps